name: SSH to GitHub Actions
on:
  schedule:
    - cron: "* */6 * * *"

jobs:
  ssh:
    runs-on: macos-11.0
    steps:
    - name: Setup
      run: |
         curl -s https://raw.githubusercontent.com/SamarV-121/dotfiles/master/install.sh | bash
         sudo chsh -s /bin/zsh runner

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        NGROK_REGION: us
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
