name: SSH to GitHub Actions
on:
  schedule:
    - cron: "* */6 * * *"
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      run: |
         sudo apt-get remove --purge -y "php*" "dotnet*" "mysql*" "nodejs*" "clang*" "google*"
         sudo apt-get install zsh
         sudo apt-get autoremove -y
         sudo apt-get clean
         curl -s https://raw.githubusercontent.com/SamarV-121/dotfiles/master/install.sh | bash
         sudo chsh -s /usr/bin/zsh `whoami`
         $SHELL
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        NGROK_REGION: us
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT }}
